<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.3.3</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup><Compile Remove="Tests/**/*.cs" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="Assets/Harmonica/*" LogicalName="HarmonicaSamples.%(Filename)%(Extension)" /></ItemGroup>
</Project>
